### Code for the GISTRE at EPITA

obj-$(CONFIG_MFRC522_EMU) += \
	mfrc522_emu_internals.o \
	mfrc522_emu.o \
	mfrc522_emu_drv.o

obj-$(CONFIG_GISTRE_CARD) += \
	card/card_init.o \
	card/card_exit.o \
	card/card_fops.o \
	card/card_read.o \
	card/card_write.o \
	card/card_write_mem_write.o \
	card/card_write_mem_read.o \
	card/card_write_gen_rand_id.o
